---
- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ii--ucspi
    - nagios--chroot
    - runit

- name: Manage group ii
  group:
    name: ii
    gid: 3001

- name: Manage user ii
  user:
    name: ii
    password: "*************"
    uid: 3001
    group: ii
    groups: []
    login_class: default
    shell: /sbin/nologin
    home: /nonexistent
    create_home: no
    comment: "irc client user"

- name: /var/ii
  file:
    path: /var/ii
    state: directory
    owner: ii
    group: ii
    mode: 0750
    follow: no
- name: /var/irc
  file:
    path: /var/irc
    state: directory
    owner: ii
    group: _nagios
    mode: 0710
    follow: no

- name: /var/ii/run
  template:
    src: ii.run
    dest: /var/ii/run
    owner: ii
    group: ii
    mode: 0500
    validate: "sh -n %s"
  notify: Reload ii
- name: /var/ii/finish
  copy:
    src: ii.finish
    dest: /var/ii/finish
    owner: ii
    group: ii
    mode: 0500
    validate: "sh -n %s"
  notify: Reload ii

- name: /etc/rc.d/ii
  copy:
    src: ii.rc
    dest: /etc/rc.d/ii
    owner: root
    group: wheel
    mode: 0555
    validate: "sh -n %s"
- name: Enable ii
  service:
    name: ii
    state: started
    enabled: yes
