---
- name: /etc/hostname.vio0
  template:
    src: hostname.vio0
    dest: /etc/hostname.vio0
    owner: root
    group: wheel
    mode: 0440

- name: /etc/resolv.conf family
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^family '
    line: "family inet6 inet4"
