---
# This comes first as we need to gather facts before setting PKG_PATH.
- hosts: all
  tasks: []
- hosts: all
  roles:
    - role: base
    - role: mail
    - role: maintenance
    - role: net
    - role: ssh
    - role: users
  environment:
    PKG_PATH: "https://assets.tfes.org/openbsd/{{ ansible_distribution_version }}/packages/{{ ansible_architecture }}:installpath"
- hosts: irc
  roles:
    - role: ngircd
  environment:
    PKG_PATH: "https://assets.tfes.org/openbsd/{{ ansible_distribution_version }}/packages/{{ ansible_architecture }}:installpath"
- hosts: nagios
  roles:
    - role: nagios
  environment:
    PKG_PATH: "https://assets.tfes.org/openbsd/{{ ansible_distribution_version }}/packages/{{ ansible_architecture }}:installpath"
- hosts: all
  roles:
    - role: pf
  environment:
    PKG_PATH: "https://assets.tfes.org/openbsd/{{ ansible_distribution_version }}/packages/{{ ansible_architecture }}:installpath"
