---
- name: /etc/ssh/sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: wheel
    mode: 0444
    validate: "/usr/sbin/sshd -tf %s"
  notify: Reload sshd

- name: Enable sshd
  service:
    name: sshd
    state: started
    enabled: yes
