#!/bin/sh

# Install patched versions of OpenBSD binaries to /usr/local.

set -e

t="$(mktemp -d)"
cd "$t"

ftp "$1" "${1%/*}/SHA256.sig"

f="${1##*/}"
signify -C -p /etc/signify/tfes-"$(uname -r|tr -d .)"-pkg.pub \
	-x SHA256.sig "$f"
gunzip "$f"
install -c -S -s -o root -g bin -m 555 "${f%.gz}" /usr/local/sbin/"${f%.gz}"

cd
rm -rf "$t"
