---
- name: /etc/pf.conf
  assemble:
    src: /etc/pf.d
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: 0400
    validate: "pfctl -nf %s"
  notify: Reload pf

- name: Reload pf
  command: pfctl -f /etc/pf.conf
