---
- name: Include user config for {{username}}
  include_vars: user:{{username}}.yml

- name: Manage group {{username}}
  group:
    name: "{{username}}"
    gid: "{{uid}}"

- name: Manage user {{username}}
  user:
    name: "{{username}}"
    password: "*************"
    uid: "{{uid}}"
    group: "{{username}}"
    groups: "{{user_groups}}"
    home: /home/{{username}}

- name: /home/{{username}}
  file:
    path: /home/{{username}}
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0750

- name: /home/{{username}}/.ssh/authorized_keys
  copy:
    src: authorized_keys:{{username}}
    dest: /home/{{username}}/.ssh/authorized_keys
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0400
