---
- name: /etc/mail/auth_palpatine
  copy:
    dest: /etc/mail/auth_palpatine
    owner: root
    group: wheel
    mode: 0400
    force: no
    content: "{{ lookup('password', '/dev/null length=64') }}\n"

- name: /etc/mail/aliases
  copy:
    src: aliases{{ v }}
    dest: /etc/mail/aliases
    owner: root
    group: wheel
    mode: 0444
  notify: newaliases

- name: /etc/mail/smtpd.conf
  template:
    src: smtpd.conf{{ v }}
    dest: /etc/mail/smtpd.conf
    owner: root
    group: wheel
    mode: 0444
    validate: "smtpd -nf %s"
  notify: Reload smtpd

- name: Enable smtpd
  service:
    name: smtpd
    state: started
    enabled: yes
