---
- name: Set OS version short fact
  set_fact:
    v: "{{ ansible_distribution_version | replace('.', '') }}"

# Common files.
- name: /etc/doas.conf
  copy:
    src: doas.conf
    dest: /etc/doas.conf
    owner: root
    group: wheel
    mode: 0444
    validate: "doas -C %s"
- name: /etc/fstab
  template:
    src: fstab
    dest: /etc/fstab
    owner: root
    group: wheel
    mode: 0444
- name: /etc/installurl
  copy:
    content: "{{ mirror }}\n"
    dest: /etc/installurl
    owner: root
    group: wheel
    mode: 0444
- name: /etc/localtime
  file:
    path: /etc/localtime
    state: link
    src: /usr/share/zoneinfo/UTC
    owner: root
    group: wheel
    follow: no
- name: /etc/pf.d
  file:
    path: /etc/pf.d
    state: directory
    owner: root
    group: wheel
    mode: 0500
    follow: no
- name: /etc/profile
  copy:
    src: profile{{ v }}
    dest: /etc/profile
    owner: root
    group: wheel
    mode: 0444
    validate: "sh -n %s"

# signify package keys
- name: /etc/signify/mtier-{{ v }}-pkg.pub
  copy:
    src: mtier-{{ v }}-pkg.pub
    dest: /etc/signify/mtier-{{ v }}-pkg.pub
    owner: root
    group: wheel
    mode: 0444
  when: ansible_distribution_version == "6.4"
- name: /etc/signify/tfes-{{ v }}-pkg.pub
  copy:
    src: tfes-{{ v }}-pkg.pub
    dest: /etc/signify/tfes-{{ v }}-pkg.pub
    owner: root
    group: wheel
    mode: 0444

# Services unnecessary on servers.
- name: Disable sndiod
  service:
    name: sndiod
    state: stopped
    enabled: no

# Users should be managed with ansible, so clean up any adduser cruft.
- name: /etc/adduser.conf
  file:
    path: /etc/adduser.conf
    state: absent
    follow: no
- name: /etc/group.bak
  file:
    path: /etc/group.bak
    state: absent
    follow: no
