---
# Common files.
- name: /etc/doas.conf
  copy:
    src: doas.conf
    dest: /etc/doas.conf
    owner: root
    group: wheel
    mode: 0444
    validate: "doas -C %s"
- name: /etc/fstab
  template:
    src: fstab
    dest: /etc/fstab
    owner: root
    group: wheel
    mode: 0444
- name: /etc/installurl
  copy:
    content: "{{ mirror }}\n"
    dest: /etc/installurl
    owner: root
    group: wheel
    mode: 0444
- name: /etc/localtime
  file:
    path: /etc/localtime
    state: link
    src: /usr/share/zoneinfo/UTC
    owner: root
    group: wheel
    follow: no
- name: /etc/pf.d
  file:
    path: /etc/pf.d
    state: directory
    owner: root
    group: wheel
    mode: 0500
    follow: no
- name: /etc/profile
  copy:
    src: profile
    dest: /etc/profile
    owner: root
    group: wheel
    mode: 0444
    validate: "sh -n %s"

- name: Install tfespatch
  copy:
    src: tfespatch
    dest: /usr/local/sbin/tfespatch
    owner: root
    group: wheel
    mode: 0555
    validate: "sh -n %s"

# signify package keys
- name: /etc/signify/mtier-64-pkg.pub
  copy:
    src: mtier-64-pkg.pub
    dest: /etc/signify/mtier-64-pkg.pub
    owner: root
    group: wheel
    mode: 0444
- name: /etc/signify/tfes-64-pkg.pub
  copy:
    src: tfes-64-pkg.pub
    dest: /etc/signify/tfes-64-pkg.pub
    owner: root
    group: wheel
    mode: 0444

# Services unnecessary on servers.
- name: Disable sndiod
  service:
    name: sndiod
    state: stopped
    enabled: no

# Users should be managed with ansible, so clean up any adduser cruft.
- name: /etc/adduser.conf
  file:
    path: /etc/adduser.conf
    state: absent
    follow: no
- name: /etc/group.bak
  file:
    path: /etc/group.bak
    state: absent
    follow: no
