---
# Common files.
- name: /etc/doas.conf
  copy:
    src: doas.conf
    dest: /etc/doas.conf
    owner: root
    group: wheel
    mode: 0444
    validate: "doas -C %s"

# Services unnecessary on servers.
- name: Disable sndiod
  service:
    name: sndiod
    state: stopped
    enabled: no
