---
# Common files.
- name: /etc/doas.conf
  copy:
    src: doas.conf
    dest: /etc/doas.conf
    owner: root
    group: wheel
    mode: 0444
    validate: "doas -C %s"
- name: /etc/profile
  copy:
    src: profile
    dest: /etc/profile
    owner: root
    group: wheel
    mode: 0444
    validate: "sh -n %s"

# signify package keys
- name: /etc/signify/mtier-64-pkg.pub
  copy:
    src: mtier-64-pkg.pub
    dest: /etc/signify/mtier-64-pkg.pub
    owner: root
    group: wheel
    mode: 0444
- name: /etc/signify/tfes-64-pkg.pub
  copy:
    src: tfes-64-pkg.pub
    dest: /etc/signify/tfes-64-pkg.pub
    owner: root
    group: wheel
    mode: 0444

# Services unnecessary on servers.
- name: Disable sndiod
  service:
    name: sndiod
    state: stopped
    enabled: no
