#!/bin/sh

for hook in /usr/local/libexec/maintenance.d/*; do
	[ -x "$hook" ] || continue
	"$hook" || exit 1
done

# Get PKG_PATH.
. /etc/profile

t="$(mktemp -dt maintenance.XXXXXXXXXX)" || exit 1
{ syspatch -l; pkg_info; } >"$t"/before

syspatch
pkg_add -u

{ syspatch -l; pkg_info; } >"$t"/after

if [ -s "$t"/before ] && cmp -s "$t"/before "$t"/after; then
	# No updates; nothing to do.
	:
else
	# Reboot into the updated system.
	shutdown -r +1 'Automated maintenance. To cancel: doas pkill shutdown'
fi

rm -r "$t"
