#!/bin/sh

for hook in /usr/local/libexec/maintenance.d/*; do
	[ -x "$hook" ] || continue
	"$hook" || exit 1
done

# Get PKG_PATH.
. /etc/profile

syspatch
pkg_add -u

# Always reboot, whether or not we installed updates. This sets the correct user
# expectation, and makes sure we know if a reboot would break anything.
shutdown -r +1 'Automated maintenance. To cancel: doas pkill shutdown'
