#!/bin/sh

# TODO: Genericise safety checks so we can use this on non-IRC servers.
/usr/local/sbin/check_irc_network || exit 1

# Get PKG_PATH.
. /etc/profile

syspatch
pkg_add -u

# Always reboot, whether or not we installed updates. This sets the correct user
# expectation, and makes sure we know if a reboot would break anything.
shutdown -r +1 'Automated maintenance. To cancel: doas pkill shutdown'
